name: 'List'
multiple: FALSE
category: 'Academy'
enabled: TRUE
fields:
  collection:
    type: json_api_collection
    label: 'JSON:API'
    options:
      '#required': TRUE
      '#default_value':
        resource: node--vactory_academy
        filters:
          - fields[node--vactory_academy]=drupal_internal__nid,path,title,field_vactory_date,field_vactory_excerpt,field_academy_duree,field_vactory_instructor,field_vactory_media,field_vactory_academy_langue,field_vactory_file,field_vactory_theme,field_vactory_youtube_videos,field_vactory_file_multiple
          - fields[taxonomy_term--vactory_academy_themes]=tid,name
          - fields[user--user]=drupal_internal__uid,display_name,created,field_about_the_author,field_date_of_birth,field_first_name,field_last_name,field_telephone
          - fields[media--image]=name,thumbnail
          - fields[file--image]=filename,uri
          - fields[file--document]=filename,uri
          - include=field_vactory_instructor,field_vactory_theme,field_vactory_media,field_vactory_media.thumbnail,field_vactory_file,field_vactory_file_multiple
          - page[offset]=0
          - page[limit]=9
          - sort=-created
        vocabularies:
          vactory_academy_themes: vactory_academy_themes

#  views:
#    type: dynamic_views
#    label: 'Views'
#    options:
#      '#required': TRUE
#      '#default_value':
#        views_id: vactory_academy
#        views_display_id: block_list
#        fields:
#          id: id
#          uuid: key
#          title: title
#          url: url
#          field_vactory_date: date
#          field_academy_duree: duration
#          field_vactory_excerpt: excerpt
#          field_vactory_theme: category
#          field_vactory_media: image
#        vocabularies:
#          vactory_academy_themes: vactory_academy_themes
